import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

import {offsets} from '../../styles/globalStyles';

const styles = StyleSheet.create({
  container: {backgroundColor: 'white', flex: 1},
  loader: {marginVertical: 100, alignItems: 'center'},
  modal: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 20,
  },
  modalContainer: {paddingTop: 10},
  marginTop10: {marginTop: 20},
  margin10: {margin: 10},
  modalScrollView: {
    flexGrow: 1,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  priceRangeContainer: {flex: 1, alignSelf: 'center'},
  priceText: {fontWeight: 'bold', fontSize: 20},
  valueContainer: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  valueInnerContainer: {
    alignItems: 'center',
    width: 50,
    padding: 5,
    borderWidth: 1,
    borderColor: 'black',
  },
  textWrapper: {
    alignItems: 'center',
    width: 100,
    padding: 5,
    borderWidth: 1,
    borderColor: 'black',
  },
  rentPressable: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 20,
    borderColor: 'black',
    borderRadius: 10,
    marginVertical: 20,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    flex: 1,
  },
  statusOfHome: {padding: 15},
  statusOfHomeText: {fontWeight: 'bold', fontSize: 20},
  forRent: {fontSize: 15, fontWeight: '600'},
  amenitiesContainer: {marginBottom: 40, padding: 15},
  amenitiesText: {fontSize: 18, fontWeight: 'bold'},
  forRentDesc: {fontSize: 12, paddingTop: 5},
  rentContainer: {flexDirection: 'column'},
  salePressable: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 20,
    borderColor: 'black',
    borderRadius: 10,
    marginVertical: 20,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    flex: 1,
  },
  showHomes: {
    flex: 1,
    alignSelf: 'center',
    borderRadius: 20,
    alignItems: 'center',
    borderColor: 'white',
    borderWidth: 1,
    width: '90%',
    backgroundColor: 'black',
    position: 'absolute',
    bottom: 0,
    height: 50,
  },
  showHomesText: {alignSelf: 'center', color: 'white'},
  filterPressable: {
    flexDirection: 'column',
    backgroundColor: 'white',
    padding: 8,
    paddingHorizontal: 20,
    marginHorizontal: 10,
    height: 46,
    alignItems: 'center',
    borderColor: 'black',
    justifyContent: 'space-evenly',
  },
  filterText: {paddingTop: 5, fontSize: 11},
  mainScrollView: {
    paddingHorizontal: 10,
    backgroundColor: 'white',
    zIndex: 2,
  },
  padding14: {paddingBottom: 14},
  padding2: {paddingTop: 2},
  padding6: {paddingTop: 10},
  loadingIndicator: {
    flex: 1,
    marginBottom: 10,
  },
  loaderList: {marginTop: wp(8), paddingHorizontal: wp(6.15)},
  padding40: {paddingBottom: 40},
  videoLoading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
  },
  videoContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  videoInnerContainer: {
    backgroundColor: 'black',
    borderRadius: 30,
    borderColor: 'white',
  },
  video: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
  },
  forSale: {flexDirection: 'column'},
  forSaleText: {fontSize: 15, fontWeight: '600'},
  forSaleDesc: {fontSize: 12, paddingTop: 5},
  image: {
    width: '100%',
    height: 500,
    resizeMode: 'cover',
    justifyContent: 'center',
    backgroundColor: 'black',
  },

  image1: {
    width: '100%',
    height: 400,
    resizeMode: 'cover',
    justifyContent: 'center',
    borderRadius: 5,
  },

  title: {
    fontSize: 30,
    fontFamily: 'Montserrat-Bold',
    color: 'white',
    marginLeft: 25,
    top: 10,
    alignSelf: 'center',
  },

  imageLocationIcon: {
    position: 'absolute',
    marginTop: 4,
    left: 5,
    bottom: 10,
  },
  ImageText: {
    position: 'absolute',
    color: 'white',
    marginTop: 4,
    fontSize: 18,
    fontWeight: 'bold',
    left: 35,
    bottom: 15,
  },

  ImageOverlay: {
    width: 250,
    height: 250,
    marginRight: 8,
    borderRadius: 10,
    position: 'absolute',
    backgroundColor: '#000',
    opacity: 0.5,
  },

  ImageOverlay1: {
    width: '100%',
    height: 250,
    alignSelf: 'center',
    borderRadius: 20,
    position: 'absolute',
    backgroundColor: '#000',
    opacity: 1,
  },

  button: {
    backgroundColor: '#fff',
    width: 200,
    marginLeft: 25,
    marginTop: 25,
    height: 46,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonText: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
  },
  searchButton: {
    backgroundColor: 'white',
    height: 60,
    borderRadius: 30,
    marginHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    zIndex: 10,
    shadowOpacity: 0.1,
    elevation: 5,
    borderWidth: 0.5,
    borderColor: '#DEDEDE',
    shadowRadius: 10,
    paddingLeft: offsets.offsetC,
    shadowOffset: {
      width: 1,
      height: 4,
    },
  },
  searchInfoWrapper: {
    justifyContent: 'center',
    marginLeft: offsets.offsetB,
  },
  searchButtonText: {
    fontSize: 16,
    fontFamily: 'Montserrat-SemiBold',
  },
  searchFilter: {
    marginRight: offsets.offsetB,
    borderWidth: 1,
    borderColor: '#DEDEDE',
  },
  button1: {
    flexDirection: 'column',
    backgroundColor: 'white',
    paddingVertical: 8,
    paddingHorizontal: wp(3),
    height: 40,
    alignItems: 'center',
    // borderWidth: 0.1,
    // borderColor: 'white',
    justifyContent: 'space-evenly',
  },
  btnTabActive: {
    // backgroundColor: 'black',
  },
  textTab: {
    fontSize: 11,
    color: '#717171',
  },
  textTabActive: {
    color: 'black',
    // fontWeight: 'bold',
    // color: 'white',
    // fontSize: 14,
  },
  mapContent: {
    alignItems: 'center',
    backgroundColor: '#0047B3',
    width: wp(22),
    left: wp(39),
    borderRadius: 20,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    padding: 12,
    position: 'absolute',
    bottom: wp(10),
  },
  filtersWrapper: {
    background: 'white',
    position: 'relative',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,.12)',
    paddingBottom: offsets.offsetA,
  },
  activeIndicator: {
    height: 2,
    backgroundColor: 'black',
    position: 'absolute',
    bottom: offsets.offsetA,
    left: wp(18.6),
  },
  contentContainerStyle: {
    paddingRight: Platform.OS === 'android' ? 20 : 0,
    backgroundColor: 'white',
  },
  mainScrollViewTop: {},
});
export default styles;
