import {StyleSheet, Dimensions, Platform} from 'react-native';

const {width} = Dimensions.get('window');
const window = Dimensions.get('window');

const fullWidth = window.width;

const styles = StyleSheet.create({
  parentContainer: {backgroundColor: 'white'},
  scrollView: {paddingBottom: 150},
  viewContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  viewingContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  flexColumn: {flexDirection: 'column'},
  viewingText: {fontWeight: 'bold', color: 'white'},
  font14: {fontSize: 14},
  callOwner: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: 'blue',
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 5,
    marginVertical: 5,
  },
  phoneIcon: {
    color: 'white',
    marginHorizontal: 5,
    transform: [{rotate: '90deg'}],
  },
  phoneIcon2: {
    color: 'black',
    marginHorizontal: 5,
    transform: [{rotate: '90deg'}],
  },
  callMarketer: {
    borderColor: 'black',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    backgroundColor: 'yellow',
    borderRadius: 5,
    paddingHorizontal: 5,
    paddingVertical: 5,
    marginVertical: 5,
  },
  white: {color: 'white'},
  black: {color: 'black'},
  marginLeft10: {marginLeft: 10},
  paddingBottom20: {paddingBottom: 20},
  flexRow: {flex: 1, flexDirection: 'row'},
  homesYouMayLike: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  similarHomes: {
    flexDirection: 'row',
    paddingHorizontal: 1,
    overflow: 'scroll',
  },
  showToggle: {
    fontWeight: 'bold',
  },
  showText: {color: 'blue', textDecorationLine: 'underline'},
  innerContainer: {flexDirection: 'column', marginTop: 16},
  heading: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  marginLeft12: {marginLeft: 12},
  labelText: {fontWeight: 'bold', fontSize: 16},
  rentIt: {color: 'blue'},
  guaranteeText: {color: 'deeppink'},
  bookingText: {
    marginTop: 4,
    fontSize: 12,
    color: '#555',
    maxWidth: '90%',
  },
  boldFont: {fontWeight: 'bold'},
  marginTop8: {marginTop: 8},
  showTextLabel: {color: 'blue', fontSize: 12},
  furnished: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  furnishedText: {fontWeight: 'bold', fontSize: 16},
  furnishedTextDesc: {
    marginTop: 4,
    fontSize: 12,
    color: '#555',
    maxWidth: '90%',
  },
  negotiable: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  negotiableText: {fontWeight: 'bold', fontSize: 16},
  negotiableTextDesc: {
    marginTop: 4,
    fontSize: 12,
    color: '#555',
    maxWidth: '90%',
  },
  verified: {flexDirection: 'row', alignItems: 'center'},
  verifiedText: {fontWeight: 'bold', fontSize: 16},
  verifiedTextLabel: {
    marginTop: 4,
    fontSize: 12,
    color: '#555',
    maxWidth: '90%',
  },
  amenitiesAvailable: {margin: 10, fontSize: 20, fontFamily: 'Montserrat-Bold'},
  amenitiesTheContainer: {flexDirection: 'row', flexWrap: 'wrap'},
  paddingHorizontal20: {paddingHorizontal: 20},
  reviewCounter: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
  },
  flexCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paddingTop20: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    paddingTop: 20,
  },
  flexRowCenter: {flexDirection: 'row', alignItems: 'center'},
  marginLeft5: {marginLeft: 5},
  writeAReview: {
    paddingHorizontal: 4,
    fontSize: 16,
    fontWeight: 'bold',
    color: 'blue',
  },
  flex: {flex: 1},
  cardPhotoPink: {
    borderTopWidth: 0.5,
    marginTop: 5,
    borderColor: 'deeppink',
  },
  cardPhotoGrey: {
    marginLeft: 40,
    borderTopWidth: 0.2,
    borderColor: 'gray',
  },
  pricesOfHome: {
    flex: 1,
    borderTopColor: 'lightgrey',
    borderTopWidth: 1,
    flexDirection: 'row',
    backgroundColor: 'white',
    position: 'absolute',
    height: 80,
    width: '100%',
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  grayColor: {color: 'gray'},
  forSale: {fontSize: 22, fontWeight: 'bold', marginHorizontal: 20},
  currencyPerPeriod: {fontSize: 22, fontWeight: 'bold', marginHorizontal: 20},
  payToRentPressable: {
    marginBottom: 10,
    backgroundColor: 'deeppink',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    width: '100%',
    marginHorizontal: 20,
    borderRadius: 5,
  },
  payToRentContainer: {marginTop: 10, marginHorizontal: 40},
  payToRent: {
    fontSize: 20,
    color: 'white',
    fontWeight: 'bold',
  },
  container: {
    margin: 20,
  },
  bedrooms: {
    marginVertical: 10,
    color: 'black',
    fontWeight: '600',
    fontSize: 14,
  },
  description: {
    fontSize: 18,
    lineHeight: 26,
    fontFamily: 'Montserrat-Bold',
  },

  hairline: {
    alignSelf: 'stretch',
    borderBottomWidth: 1,
    borderBottomColor: 'lightgrey',
    marginTop: 10,
    marginBottom: 10,
  },
  prices: {
    fontSize: 18,
    marginVertical: 10,
  },
  oldPrice: {
    color: 'darkgray',
    textDecorationLine: 'line-through',
  },
  newPrice: {
    fontWeight: 'bold',
  },
  totalPrice: {
    color: 'darkgray',
    textDecorationLine: 'underline',
  },
  longDescription: {
    fontSize: 16,
    lineHeight: 24,
    marginVertical: 20,
  },
  sliderContainer: {
    height: 200,
    width: '90%',
    marginTop: 10,
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 8,
  },

  wrapper: {},

  slide: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRadius: 8,
  },
  sliderImage: {
    height: '100%',
    width: '100%',
    alignSelf: 'center',
    borderRadius: 8,
  },
  amenitiesContainer: {
    marginVertical: 20,
  },
  amenityCard: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#e5e5e5',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  amenityText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 10,
  },
  itemContainer: {
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#fff',
    width: 200,
    marginRight: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.5,
        shadowRadius: 4,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  imageContainer: {
    width: '100%',
    height: 150,
    overflow: 'hidden',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  detailsContainer: {
    padding: 8,
  },
  title: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 4,
    textAlign: 'left',
  },
  location: {
    fontSize: 12,
    color: '#666',
    textAlign: 'left',
    marginBottom: 4,
  },
  price: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'blue',
    textAlign: 'left',
  },
  loadMoreButton: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingVertical: 8,
    paddingHorizontal: 16,
    marginTop: 16,
    alignSelf: 'center',
  },
  loadMoreText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  loadMore: {
    alignSelf: 'center',
    color: '#666',
    fontSize: 16,
    marginVertical: 16,
  },
  card: {
    borderRadius: 10,
    borderWidth: 0.5,
    borderColor: 'gray',
    padding: 10,
    width: 150,
    margin: 5,
    height: 100,
    justifyContent: 'center',
    backgroundColor: 'white',
    elevation: 2, // add a shadow effect for Android
    shadowColor: 'gray', // add a shadow effect for iOS
    shadowOpacity: 0.5,
    shadowOffset: {
      width: 0,
      height: 2,
    },
  },
  cardText: {
    color: 'blue',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 15,
    textAlign: 'center',
  },
  cardItem: {
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: 10,
  },
  videoWrapper: {
    width: width * 0.3,
    height: width * 0.4,
    borderRadius: 15,
    overflow: 'hidden',
    marginRight: 10,
    backgroundColor: '#000',
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
  },
  video: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
  },
  loadingIndicator: {
    position: 'absolute',
    alignSelf: 'center',
    top: '50%',
  },
  fullscreenVideo: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 10 : 60,
    left: 20,
    width: fullWidth - 40,
    height: ((fullWidth - 40) * 9) / 16,
    borderRadius: 15,
    zIndex: 9999,
    backgroundColor: '#000',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scheduleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 5,
    padding: 10,
    backgroundColor: 'black',
    // justifyContent: 'space-between',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 100,
    left: 100,
    right: 100,
    bottom: 100,
    backgroundColor: 'white',
    borderRadius: 20,
    height: '20%',
    width: '50%', // You can change the background color and opacity as needed
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 1,
    zIndex: 999, // Ensure this value is higher than the zIndex of the DateTimePickerModal
  },
  loadingText: {
    marginTop: 10, // Add some space between the ActivityIndicator and the text
    fontSize: 16,
    fontWeight: 'bold',
    zIndex: 999,
  },
  modal: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: '80%',
  },
  modalTitle: {
    fontSize: 20,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 10,
  },
  submitButton: {
    backgroundColor: 'dodgerblue',
    borderRadius: 5,
    alignItems: 'center',
    padding: 5,
  },
  submitText: {
    color: 'white',
  },
});

export default styles;
