-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgqEHrED2oMQiGIjnn
N8SiGFWbO5s9IHc5oJC7+barzIugCgYIKoZIzj0DAQehRANCAASuz5304lcnSdE6
PjhgOHNorDYTGRwCBvikdMvJXDs1AzGUq+4w1zrPHpRhuoLnNsJQctOX/EGVVtVk
+QEaKFlK
-----END PRIVATE KEY-----