/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a2fb8688-9477-4c7b-a472-f9df3db918bc",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_C9CZyfFZu",
    "aws_user_pools_web_client_id": "5tjrvc733u8b45dj1cg64j1qcs",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6fh6r2ls2fbtrl36ftl4lmc4x4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ceryuzsswnfgpbstxmhi37nqyu",
    "aws_cloud_logic_custom": [
        {
            "name": "tinggPaymentGateway",
            "endpoint": "https://i08fhhbxwk.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_mobile_analytics_app_id": "93e934849ea24093a4610fb26fb3a34f",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_user_files_s3_bucket": "pics175634-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
