#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git rev-parse --abbrev-ref HEAD)
temp_branch="temp-commit-branch"

echo "Bumping version"
npm run bump:reactnative

echo "Checking out to $temp_branch"
git checkout -B $temp_branch

git add -A
git commit -m "Bump version"

git checkout $current_branch
git merge $temp_branch

git branch -d $temp_branch
