name: Checks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  install_lint_testrun:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installation
        run: |
          sudo npm install --global yarn@1.22.5
          yarn install

      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extracted_branch

      - name: Branch Name
        run: |
          echo ${{ steps.extracted_branch.outputs.branch }}

      - name: Latest Commit on Current Branch
        run: |
          git log -n 1 --pretty=format:%h -- .

      - name: Lintable Files
        run: |
          git diff --diff-filter=RM --name-only origin/main..$(git log -n 1 --pretty=format:%h -- . | xargs)

      - name: Lint
        run: |
          npx eslint --no-inline-config --fix-dry-run $(git diff --diff-filter=RM --name-only origin/main..$(git log -n 1 --pretty=format:%h -- . | xargs) '**/*.js')

      - name: Inject environment variables
        run: |
          cat << EOF > .env
          REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
          EOF

      # - name: Run tests
      #   run: npm run test
