name: Performance Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Installation
      run: |
        sudo npm install --global yarn@1.22.5
        yarn install

    - name: Run Metro Bundler
      run: npm start &

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v7
      with:
        configPath: lighthouserc.json